spring:
  application:
    name: user

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instence:
      prefer-ip-address: true
      metadata-map:
        my-metadata: 自定义元数据
